#!/usr/bin/env ruby -I.
# A daisy executor
#
# usage:
#   ./daisy example.daisy # to run a file
#   ./daisy               # to start an interactive console
#
# on Windows run with: ruby -I. daisy [options]

require 'runtime/interpreter'

interpreter = Interpreter.new

# If a file is given we should run it.
if file = ARGV.first
  interpreter.eval(File.read(file))
else
  puts "If we were working properly, we'd have a console here"
end

