#!/usr/bin/env ruby -I.
# A daisy executor
#
# usage:
#   ./daisy example.daisy # to run a file
#   ./daisy               # to start an interactive console
#
# on Windows run with: ruby -I. daisy [options]

require 'runtime/interpreter'
require 'readline'
require 'optparse'

options = { "debug" => false }
OptionParser.new do |opts|
  opts.banner = "Usage:
    ./daisy example.daisy # to run a file
    ./daisy               # to start an interactive console "

  opts.separator ""

  opts.on("-d", "--debug", "Run in debug mode") do
    options["debug"] = true
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end.parse!

interpreter = Interpreter.new(options["debug"])

# If a file is given we should run it.
if file = ARGV.first
  interpreter.eval(File.read(file))
else
  puts "Daisy Console (CTRL+D to quit)"
  while line = Readline::readline(">> ", true)
    value = interpreter.eval(line)
    rvalue = value.ruby_value
    puts "=> #{rvalue}" unless rvalue.nil?
    puts "=> (none)" if rvalue.nil?
  end
end

